# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 16:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mdb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disease',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='disease',
            name='published_date',
        ),
    ]
