# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 22:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mdb', '0003_auto_20170713_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disease',
            name='symptoms',
        ),
    ]
