# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdb', '0004_remove_disease_symptoms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='name',
            field=models.TextField(),
        ),
    ]
