# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdb', '0005_auto_20170713_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='symptoms',
            name='symptom',
            field=models.CharField(max_length=200),
        ),
    ]
